services:
  php-environment:
    container_name: php-apache
    build:
      context: ./  # Certifique-se de que está apontando para o diretório correto
      dockerfile: ./Dockerfile  # Caminho do seu Dockerfile
    volumes:
      - ../app:/var/www/html  # Se você estiver usando o volume para vincular a pasta app ao contêiner
    ports:
      - 8000:80
  mysql: 
    container_name: "mysql"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'erp'
      MYSQL_USER: 'mysql_user'
      MYSQL_PASSWORD: 'mysql123'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATA_DIR: '/var/lib/mysql' 
      MYSQL_LOG_DIR: '/var/log/mysql'
    ports:
      - '33100:3306'
    volumes:
      - ../docker/init/mysql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
